### ISSUE TITLE
connector.s3db fehlt / is missing

### ISSUE THREAD

**Issue by saschadd** [jtl-software/connector-gambio-gx3#3]
Hallo,
die Datei connector.s3db fehlt im Verzeichnis db, somit ist ein build nicht möglich.

Hi
the file connector.s3db is missing in directory db therefore a build is not possible.

**Comment by drieschel** [comment]
Hi Sascha,

you can simply create this file.

**Comment by saschadd** [comment]
Hi Immanuel,
is it an empty sqlite-file or how do i create it correctly?
The one in the archive i download from JTL customer centers has some data inside.

**Comment by drieschel** [comment]
Maybe it's a better idea to remove this file completely from the build process. The file will be created on demand when it's needed I think.
